package com.devil.phoenixproject.data.migration

import co.touchlab.kermit.Logger
import com.devil.phoenixproject.data.repository.SqlDelightPersonalRecordRepository
import com.devil.phoenixproject.data.repository.normalizeWorkoutModeKey
import com.devil.phoenixproject.domain.model.PRType
import com.devil.phoenixproject.database.Routine
import com.devil.phoenixproject.database.RoutineExercise
import com.devil.phoenixproject.database.VitruvianDatabase
import com.devil.phoenixproject.database.WorkoutSession
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

/**
 * Manages data migrations on app startup.
 * Call [checkAndRunMigrations] after Koin is initialized.
 * Call [close] when done to prevent memory leaks.
 */
class MigrationManager(
    private val database: VitruvianDatabase
) {
    private val log = Logger.withTag("MigrationManager")
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val queries get() = database.vitruvianDatabaseQueries

    private data class RoutineNameResolutionContext(
        val routineNameById: Map<String, String>,
        val routineIdByExerciseId: Map<String, String>,
        val uniqueRoutineNameByExerciseId: Map<String, String>,
        val uniqueRoutineNameByExerciseName: Map<String, String>
    )

    /**
     * Check for and run any pending migrations.
     * This should be called once on app startup.
     */
    fun checkAndRunMigrations() {
        scope.launch {
            try {
                runMigrations()
            } catch (e: Exception) {
                log.e(e) { "Migration failed" }
            }
        }
    }

    private suspend fun runMigrations() {
        cleanupFabricatedRoutineSessionIds()
        normalizeLegacyWorkoutModes()
        backfillLegacyWorkoutRoutineNames()
        repairPersonalRecordsFromWorkoutHistory()
    }

    /**
     * Remove fabricated `legacy_session_*` routineSessionIds that were incorrectly
     * generated by an earlier version of the export/import code. These synthetic IDs
     * break history grouping by making every session appear as a separate routine execution.
     */
    private fun cleanupFabricatedRoutineSessionIds() {
        val sessions = runCatching { queries.selectAllSessionsSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load workout sessions for routineSessionId cleanup" }
                return
            }

        var cleaned = 0
        database.transaction {
            sessions.forEach { session ->
                val rawId = session.routineSessionId ?: return@forEach
                // Only strip IDs that exactly match the known fabrication pattern
                if (rawId.equals("legacy_session_${session.id}", ignoreCase = true)) {
                    queries.updateSessionRoutineSessionId(
                        routineSessionId = null,
                        id = session.id
                    )
                    cleaned++
                }
            }
        }

        if (cleaned > 0) {
            log.i { "Cleaned $cleaned fabricated legacy_session_* routineSessionIds" }
        }
    }

    private fun backfillLegacyWorkoutRoutineNames() {
        val sessions = runCatching { queries.selectAllSessionsSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load workout sessions for legacy routine-name backfill" }
                return
            }
        if (sessions.isEmpty()) return

        val routines = runCatching { queries.selectAllRoutinesSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load routines for legacy routine-name backfill" }
                emptyList()
            }
        val routineExercises = runCatching { queries.selectAllRoutineExercisesSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load routine exercises for legacy routine-name backfill" }
                emptyList()
            }
        val resolutionContext = buildRoutineNameResolutionContext(routines, routineExercises)

        var updatedNameRows = 0
        var updatedIdRows = 0
        database.transaction {
            sessions.forEach { session ->
                // Backfill routineId for sessions that have a routineSessionId but no routineId
                if (session.routineId == null && session.routineSessionId != null) {
                    val resolvedRoutineId = resolveRoutineIdForSession(session, resolutionContext)
                    if (resolvedRoutineId != null) {
                        queries.updateSessionRoutineId(
                            routineId = resolvedRoutineId,
                            id = session.id
                        )
                        updatedIdRows++
                    }
                }

                // Backfill routine name (or clear garbage names that can't be inferred)
                val updatedRoutineName = resolveRoutineNameForSession(session, resolutionContext)
                if (updatedRoutineName == session.routineName) return@forEach
                // If resolved is null and current is also null, nothing to change
                if (updatedRoutineName == null && session.routineName == null) return@forEach
                queries.updateSessionRoutineName(
                    routineName = updatedRoutineName,
                    id = session.id
                )
                updatedNameRows++
            }
        }

        if (updatedNameRows > 0 || updatedIdRows > 0) {
            log.i { "Legacy routine backfill: updated $updatedNameRows names, $updatedIdRows routineIds" }
        }
    }

    private fun normalizeLegacyWorkoutModes() {
        normalizeLegacySessionModes()
        normalizeLegacyPersonalRecordModes()
    }

    private fun normalizeLegacySessionModes() {
        val sessions = runCatching { queries.selectAllSessionsSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load workout sessions for mode normalization" }
                return
            }

        var updated = 0
        database.transaction {
            sessions.forEach { session ->
                val normalizedMode = normalizeWorkoutModeKey(session.mode)
                if (normalizedMode == session.mode) return@forEach

                queries.updateSessionMode(
                    mode = normalizedMode,
                    id = session.id
                )
                updated++
            }
        }

        if (updated > 0) {
            log.i { "Normalized workout mode keys for $updated workout sessions" }
        }
    }

    private fun normalizeLegacyPersonalRecordModes() {
        val records = runCatching { queries.selectAllRecords(profileId = "default").executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load personal records for mode normalization" }
                return
            }

        var updated = 0
        var merged = 0
        database.transaction {
            records.forEach { record ->
                val normalizedMode = normalizeWorkoutModeKey(record.workoutMode)
                if (normalizedMode == record.workoutMode) return@forEach

                val canonicalRecord = queries.selectPR(
                    exerciseId = record.exerciseId,
                    workoutMode = normalizedMode,
                    prType = record.prType,
                    phase = record.phase,
                    profileId = "default"
                ).executeAsOneOrNull()

                if (canonicalRecord == null || shouldReplacePersonalRecord(record, canonicalRecord)) {
                    queries.upsertPR(
                        exerciseId = record.exerciseId,
                        exerciseName = record.exerciseName,
                        weight = record.weight,
                        reps = record.reps,
                        oneRepMax = record.oneRepMax,
                        achievedAt = record.achievedAt,
                        workoutMode = normalizedMode,
                        prType = record.prType,
                        volume = record.volume,
                        phase = record.phase,
                        profile_id = "default"
                    )
                    updated++
                } else {
                    merged++
                }

                queries.deletePRByKey(
                    exerciseId = record.exerciseId,
                    workoutMode = record.workoutMode,
                    prType = record.prType,
                    phase = record.phase,
                    profile_id = "default"
                )
            }
        }

        if (updated > 0 || merged > 0) {
            log.i { "Normalized personal record mode keys: updated $updated rows, merged $merged legacy duplicates" }
        }
    }

    private suspend fun repairPersonalRecordsFromWorkoutHistory() {
        val sessions = runCatching { queries.selectAllSessionsSync().executeAsList() }
            .getOrElse { error ->
                log.e(error) { "Failed to load workout sessions for PR repair" }
                return
            }
            .sortedBy { it.timestamp }

        if (sessions.isEmpty()) return

        val personalRecordRepository = SqlDelightPersonalRecordRepository(database)
        var repairedSessions = 0
        var repairedRecords = 0

        sessions.forEach { session ->
            val exerciseId = sanitizeLegacyLabel(session.exerciseId) ?: return@forEach
            if (session.isJustLift != 0L) return@forEach

            val normalizedMode = normalizeWorkoutModeKey(session.mode)
            if (normalizedMode == "Echo") return@forEach

            val reps = session.workingReps.toInt()
            if (reps <= 0) return@forEach

            val achievedWeightKg = session.heaviestLiftKg?.toFloat() ?: session.weightPerCableKg.toFloat()
            val configuredWeightKg = session.weightPerCableKg.toFloat()
            if (achievedWeightKg <= 0f || configuredWeightKg <= 0f) return@forEach

            val brokenPRs = runCatching {
                personalRecordRepository.updatePRsIfBetter(
                    exerciseId = exerciseId,
                    weightPRWeightPerCableKg = achievedWeightKg,
                    volumePRWeightPerCableKg = configuredWeightKg,
                    reps = reps,
                    workoutMode = normalizedMode,
                    timestamp = session.timestamp,
                    profileId = "default"
                ).getOrThrow()
            }.getOrElse { error ->
                log.e(error) { "Failed to repair PRs for session ${session.id}" }
                return@forEach
            }

            if (brokenPRs.isNotEmpty()) {
                repairedSessions++
                repairedRecords += brokenPRs.size
            }
        }

        if (repairedRecords > 0) {
            log.i { "Repaired $repairedRecords PR records from $repairedSessions workout sessions" }
        }
    }

    private fun shouldReplacePersonalRecord(
        candidate: com.devil.phoenixproject.database.PersonalRecord,
        current: com.devil.phoenixproject.database.PersonalRecord
    ): Boolean {
        return when (candidate.prType) {
            PRType.MAX_VOLUME.name -> when {
                candidate.volume > current.volume -> true
                candidate.volume < current.volume -> false
                else -> candidate.achievedAt > current.achievedAt
            }
            else -> when {
                candidate.weight > current.weight -> true
                candidate.weight < current.weight -> false
                candidate.oneRepMax > current.oneRepMax -> true
                candidate.oneRepMax < current.oneRepMax -> false
                else -> candidate.achievedAt > current.achievedAt
            }
        }
    }

    private fun resolveRoutineNameForSession(
        session: WorkoutSession,
        routineNameResolutionContext: RoutineNameResolutionContext
    ): String? {
        val existingRoutineName = sanitizeRoutineName(session.routineName)
        val inferredRoutineName = inferRoutineName(session, routineNameResolutionContext)
        val existingLooksLikeExercisePlaceholder =
            normalizeExerciseToken(existingRoutineName) == normalizeExerciseToken(session.exerciseName)

        return when {
            session.isJustLift != 0L -> "Just Lift"
            inferredRoutineName != null && (existingRoutineName == null || existingLooksLikeExercisePlaceholder) -> inferredRoutineName
            existingRoutineName != null && !existingLooksLikeExercisePlaceholder -> existingRoutineName
            else -> null  // Can't determine routine - leave null (standalone exercise)
        }
    }

    /**
     * Attempt to resolve the routineId for a legacy session by checking if the session's
     * exerciseId uniquely belongs to a single routine.
     */
    private fun resolveRoutineIdForSession(
        session: WorkoutSession,
        routineNameResolutionContext: RoutineNameResolutionContext
    ): String? {
        val exerciseId = sanitizeLegacyLabel(session.exerciseId) ?: return null
        return routineNameResolutionContext.routineIdByExerciseId[exerciseId]
    }

    private fun inferRoutineName(
        session: WorkoutSession,
        routineNameResolutionContext: RoutineNameResolutionContext
    ): String? {
        val byExerciseId = sanitizeLegacyLabel(session.exerciseId)?.let { exerciseId ->
            routineNameResolutionContext.uniqueRoutineNameByExerciseId[exerciseId]
        }
        if (byExerciseId != null) return byExerciseId

        val normalizedExerciseName = normalizeExerciseToken(session.exerciseName) ?: return null
        return routineNameResolutionContext.uniqueRoutineNameByExerciseName[normalizedExerciseName]
    }

    private fun buildRoutineNameResolutionContext(
        routines: List<Routine>,
        routineExercises: List<RoutineExercise>
    ): RoutineNameResolutionContext {
        val routineNameById = routines.associate { routine ->
            routine.id to sanitizeEntityName(routine.name, "Unnamed Routine")
        }

        // Build exerciseId → routineId map for sessions where exercise uniquely belongs to one routine
        val routineIdsByExerciseId = mutableMapOf<String, MutableSet<String>>()
        routineExercises.forEach { exercise ->
            val exerciseId = sanitizeLegacyLabel(exercise.exerciseId) ?: return@forEach
            routineIdsByExerciseId.getOrPut(exerciseId) { mutableSetOf() }.add(exercise.routineId)
        }
        val routineIdByExerciseId = mutableMapOf<String, String>()
        routineIdsByExerciseId.forEach { (exerciseId, routineIds) ->
            if (routineIds.size == 1) {
                routineIdByExerciseId[exerciseId] = routineIds.first()
            }
        }

        val nonTemplateRoutineIds = routines
            .asSequence()
            .filterNot { it.id.startsWith("cycle_routine_") }
            .map { it.id }
            .toSet()

        fun collectUniqueRoutineNamesByExerciseId(
            allowedRoutineIds: Set<String>? = null
        ): Map<String, String> {
            val routineIdsByExerciseId = mutableMapOf<String, MutableSet<String>>()
            routineExercises.forEach { exercise ->
                if (allowedRoutineIds != null && exercise.routineId !in allowedRoutineIds) return@forEach
                val exerciseId = sanitizeLegacyLabel(exercise.exerciseId) ?: return@forEach
                routineIdsByExerciseId.getOrPut(exerciseId) { mutableSetOf() }.add(exercise.routineId)
            }

            val uniqueRoutineNames = mutableMapOf<String, String>()
            routineIdsByExerciseId.forEach { (exerciseId, routineIds) ->
                if (routineIds.size != 1) return@forEach
                val routineId = routineIds.first()
                val routineName = routineNameById[routineId] ?: return@forEach
                uniqueRoutineNames[exerciseId] = routineName
            }
            return uniqueRoutineNames
        }

        fun collectUniqueRoutineNamesByExerciseName(
            allowedRoutineIds: Set<String>? = null
        ): Map<String, String> {
            val routineIdsByExerciseName = mutableMapOf<String, MutableSet<String>>()
            routineExercises.forEach { exercise ->
                if (allowedRoutineIds != null && exercise.routineId !in allowedRoutineIds) return@forEach
                val normalizedExerciseName = normalizeExerciseToken(exercise.exerciseName) ?: return@forEach
                routineIdsByExerciseName.getOrPut(normalizedExerciseName) { mutableSetOf() }.add(exercise.routineId)
            }

            val uniqueRoutineNames = mutableMapOf<String, String>()
            routineIdsByExerciseName.forEach { (exerciseName, routineIds) ->
                if (routineIds.size != 1) return@forEach
                val routineId = routineIds.first()
                val routineName = routineNameById[routineId] ?: return@forEach
                uniqueRoutineNames[exerciseName] = routineName
            }
            return uniqueRoutineNames
        }

        val uniqueFromNonTemplateById = collectUniqueRoutineNamesByExerciseId(
            allowedRoutineIds = nonTemplateRoutineIds.takeIf { it.isNotEmpty() }
        )
        val uniqueFromAllById = collectUniqueRoutineNamesByExerciseId()
        val uniqueRoutineNameByExerciseId = uniqueFromAllById.toMutableMap().apply {
            putAll(uniqueFromNonTemplateById)
        }
        val uniqueFromNonTemplateByName = collectUniqueRoutineNamesByExerciseName(
            allowedRoutineIds = nonTemplateRoutineIds.takeIf { it.isNotEmpty() }
        )
        val uniqueFromAllByName = collectUniqueRoutineNamesByExerciseName()
        val uniqueRoutineNameByExerciseName = uniqueFromAllByName.toMutableMap().apply {
            putAll(uniqueFromNonTemplateByName)
        }

        return RoutineNameResolutionContext(
            routineNameById = routineNameById,
            routineIdByExerciseId = routineIdByExerciseId,
            uniqueRoutineNameByExerciseId = uniqueRoutineNameByExerciseId,
            uniqueRoutineNameByExerciseName = uniqueRoutineNameByExerciseName
        )
    }

    /**
     * Sanitize a routineSessionId, also filtering out fabricated `legacy_session_*` IDs
     * that were incorrectly generated by an earlier version of the export/import code.
     */
    private fun sanitizeRoutineSessionId(raw: String?): String? {
        val sanitized = sanitizeLegacyLabel(raw) ?: return null
        if (sanitized.startsWith("legacy_session_", ignoreCase = true)) return null
        return sanitized
    }

    private fun sanitizeEntityName(raw: String?, fallback: String): String {
        return sanitizeLegacyLabel(raw) ?: fallback
    }

    private fun sanitizeLegacyLabel(raw: String?): String? {
        val trimmed = raw?.trim().orEmpty()
        if (trimmed.isEmpty()) return null
        if (trimmed.equals("null", ignoreCase = true)) return null
        if (!trimmed.any { it.isLetterOrDigit() }) return null
        return trimmed
    }

    /**
     * Generic placeholder routine names set by external imports (e.g. Vitruvian cloud).
     * These don't identify a real routine and should be treated as null/unknown.
     */
    private val GARBAGE_ROUTINE_NAMES = setOf(
        "imported strength training session"
    )

    private fun sanitizeRoutineName(raw: String?): String? {
        val sanitized = sanitizeLegacyLabel(raw) ?: return null
        if (sanitized.lowercase().trim() in GARBAGE_ROUTINE_NAMES) return null
        return sanitized
    }

    private fun normalizeExerciseToken(raw: String?): String? {
        val sanitized = sanitizeLegacyLabel(raw) ?: return null
        val collapsedWhitespace = sanitized
            .lowercase()
            .replace(Regex("\\s+"), " ")
            .trim()
        return collapsedWhitespace.ifEmpty { null }
    }

    /**
     * Cancels the coroutine scope to prevent memory leaks.
     * Should be called when the MigrationManager is no longer needed.
     */
    fun close() {
        scope.cancel()
        log.d { "MigrationManager scope cancelled" }
    }
}
